version: '3.8'

services:
  api:
    build:
      context: ./OfferProject
      dockerfile: Dockerfile
    ports:
      - "5212:5212"
    depends_on:
      - mysqldb
    networks:
      - my-network

  angular:
    build: 
      context: ./OfferCaseUI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - my-network
  
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "tempdb"
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network: